"""Shared research state definition for the Doxa agent system."""

from __future__ import annotations

from typing import Any, TypedDict


class ResearchState(TypedDict):
    """Shared state passed between all agents in the pipeline.

    Attributes:
        ticker: Uppercase stock ticker symbol (e.g. "NVDA").
        market_data: Current price, market cap, 52-week range, price history,
            institutional depth data (5-year history, dividends, splits, beta, etc).
        financials: Revenue, net income, cash, debt from company filings.
        news: Headlines collected by the SentimentAgent.
        sentiment_score: Sentiment score from headline analysis (-1.0 to 1.0).
        sentiment_rationale: Claude's explanation for the sentiment score.
        sentiment_confidence: Confidence score for sentiment analysis (0-100).
        sentiment_confidence_details: Detailed confidence breakdown.
        alternative_data: Alternative data sources for sentiment analysis including:
            - insider_trading: Insider buy/sell transactions from SEC Form 4
            - short_interest: Short interest percentage and trend analysis
            - options_flow: Unusual options activity (None for MVP)
            - social_media: Social sentiment aggregation (None for MVP)
            - contradictions: Management guidance vs market signal contradictions
        quant_analysis: DEPRECATED - Absorbed into valuation_analysis (kept
            for backward compatibility).
        valuation_analysis: Comprehensive valuation including DCF, comps,
            quantitative analysis (DuPont, Altman Z-Score, financial ratios,
            trends), and confidence scoring.
        regulatory_analysis: SEC filing analysis from RegulatoryAgent including:
            - Single-year risks: risk_factors (list[str]), legal_proceedings (str),
              risk_score ("Low"|"Medium"|"High"), filing_date (str), cik (str),
              filing_url (str)
            - Multi-year risk evolution: multi_year_filings (list[dict] with year,
              filing_date, risk_factors_text), risk_evolution (dict with new_risks,
              removed_risks, escalated_risks, trend, interpretation)
            - Management signals: insider_ownership_pct (float|None),
              institutional_ownership_pct (float|None), ceo_ownership_value (str|None),
              signal ("positive"|"negative"|"neutral")
            - Confidence metrics: confidence (float 0-100), confidence_details (dict
              with filings_analyzed, insider_data_available, claude_success,
              claude_evolution_success)
        human_notes: Subjective analyst notes entered during the pipeline.
        final_report: Markdown research report generated by the WriterAgent.
        errors: List of non-fatal error messages accumulated during processing.
        provenance_metadata: Data provenance tracking for audit trail.
        insights_board: Cross-domain signals posted by agents during pipeline
            execution. Each entry conforms to: {agent: str, category: str,
            signal: str, confidence: float, timestamp: str (ISO 8601 UTC)}.
            Posted by MarketData/Valuation/Regulatory/Sentiment agents;
            consumed by WriterAgent and EditorAgent.
    """

    ticker: str
    market_data: dict[str, Any]
    financials: dict[str, Any]
    news: list[dict[str, Any]]
    sentiment_score: float
    sentiment_rationale: str
    sentiment_confidence: float
    sentiment_confidence_details: dict[str, Any]
    alternative_data: dict[str, Any]
    quant_analysis: dict[str, Any]
    valuation_analysis: dict[str, Any]
    regulatory_analysis: dict[str, Any]
    human_notes: str
    final_report: str
    errors: list[str]
    provenance_metadata: dict[str, Any]
    insights_board: list[dict[str, Any]]


def create_initial_state(ticker: str) -> ResearchState:
    """Create a blank ResearchState for the given ticker.

    Args:
        ticker: Stock ticker symbol. Will be normalized to uppercase.

    Returns:
        A ResearchState with empty defaults for all fields.

    Raises:
        ValueError: If ticker is empty or whitespace-only.
    """
    stripped = ticker.strip()
    if not stripped:
        raise ValueError("Ticker must not be empty")
    return ResearchState(
        ticker=stripped.upper(),
        market_data={},
        financials={},
        news=[],
        sentiment_score=0.0,
        sentiment_rationale="",
        sentiment_confidence=0.0,
        sentiment_confidence_details={},
        alternative_data={},
        quant_analysis={},
        valuation_analysis={},
        regulatory_analysis={},
        human_notes="",
        final_report="",
        errors=[],
        provenance_metadata={},
        insights_board=[],
    )
